<div class="customer-account-repiitcredits">
    <div class="page-title">
        <h1><?php echo $this->__('Repiit Credits') ?></h1>
    </div>
    <div class="repiitcredits">
        <div class="form-group">

            <div class="form-group">
                <div class="row">
                        <div class="col-xs-12 col-sm-6">
                            <?php echo $this->__('My credit balance: ') ?><span class="regular-price"><span><?php echo $this->getBalanceAccount() ?></span></span>
                        </div>
                </div>
            </div>
        </div>
        <?php echo $this->getGridHtml() ?>
    </div>
</div>