<?php
    $_product = Mage::registry('current_product');
    $helper = Mage::helper('Repiit_Subscription');
echo "Test";
    if ($_product->getSubscriptionActiv() || $helper->childrenHasSubscriptionActiv($_product)) :

        $_helper = $this->helper('catalog/output');

        $buttonTitle = 'Subscribe';

?>
<?php if($_additional = $this->getSubscriptionData()): ?>
    <div class="product-shop" id="product-subscription-wrapper">
        <h3><?php echo $this->__('Subscription Information') ?></h3>
        <table class="data-table" id="product-attribute-specs-table">
            <col width="25%" />
            <col />
            <tbody>
            <?php foreach ($_additional as $_data): ?>
                <tr>
                    <th class="label">
                        <?php echo $this->escapeHtml($this->__($_data['label'])) ?>
                    </th>
                    <td class="data">
                        <span id="repiitsubscripiton_attr_<?php echo $_data['code'] ?>"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></span>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
    <?php endif;?>

            <form action="<?php echo Mage::helper('Repiit_Subscription')->getSubscriptionUrl() ?>" method="get" id="product_subscription_form">
                <input type="hidden" name="partenerid" id="partenerid" value="" />
                <input type="hidden" name="key" id="key" value="" />

                <input type="hidden" name="DATASET" id="DATASET" value="<?php echo Mage::getModel('repiit_subscription/api')->getDataset() ?>" />
                <input type="hidden" name="EMAIL" id="EMAIL" value="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()) echo Mage::getSingleton('customer/session')->getCustomer()->getEmail(); ?>" />
                <input type="hidden" name="ITEMNUMBER" id="ITEMNUMBER" value="<?php echo $_product->getSku() ?>" />

                <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
                <span><?php echo $this->__('You need to be logged in to subscribe') ?></span>
                <?php else : ?>
                <button type="submit" name="submit" class="button btn-cart" id="button_subscriptionrepiit" <?php echo ($_additional['subscription_activ']['value'] == 'Yes')?'':'disabled' ?>><?php echo $this->__('Subscribe') ?></button>
                <?php endif; ?>
            </form>

            <script type="text/javascript">
                //<![CDATA[
                var productSubscriptionForm = new VarienForm('product_subscription_form');
            </script>
        </div>
<?php endif; ?>

<?php
if ($_product->getTypeId() == 'configurable') :
?>

    <script>
        var SubscriptionProducts = <?php echo str_replace('"','\'',$this->getSubscriptionDataConfigurable()) ?>;
    </script>

<script>
    function getSimpleProductId() {
        var productCandidates = [];
        jQuery.each(spConfig.settings, function (selectIndex, select) {
            var attributeId = select.id.replace('attribute', '');
            var selectedValue = select.options[select.selectedIndex].value;

            jQuery.each(spConfig.config.attributes[attributeId].options, function(optionIndex, option) {
                if (option.id == selectedValue) {
                    var optionProducts = option.products;

                    if (productCandidates.length == 0) {
                        productCandidates = optionProducts;
                    } else {
                        var productIntersection = [];
                        jQuery.each(optionProducts, function (productIndex, productId) {
                            if (productCandidates.indexOf(productId) > -1) {
                                productIntersection.push(productId);
                            }
                        });
                        productCandidates = productIntersection;
                    }
                }
            });
        });
        return (productCandidates.length == 1) ? productCandidates[0] : null;
    }


    jQuery(document).ready(function() {
        jQuery("<?php echo Mage::getStoreConfig('repiitsubscription/api/js_selector_config') ?>").on('click', function() {
            // Your code here
            var simpleId = getSimpleProductId();

            var simpleSubscriptionProduct = SubscriptionProducts[simpleId];

            if (simpleSubscriptionProduct)
            {
                for (var key in simpleSubscriptionProduct)
                {

                    jQuery('#repiitsubscripiton_attr_' + key).html(simpleSubscriptionProduct[key].value);

                }

                if (simpleSubscriptionProduct['subscription_activ'].value == 'Yes') jQuery('#button_subscriptionrepiit').attr('disabled', false);
                else jQuery('#button_subscriptionrepiit').attr('disabled', true);

                jQuery('#ITEMNUMBER').attr('value',simpleSubscriptionProduct['sku'].value);
            }
            else
            {
                jQuery('#button_subscriptionrepiit').attr('disabled', true);
            }

        });
    });
</script>
<?php endif; ?>